#!/usr/bin/env bash

set -euo pipefail

readonly MAPL3_SAMPLE_URL="https://huggingface.co/datasets/AICONSlab/MIRACL/resolve/dev/sample_data/mapl3"
readonly MAPL3_DATASET_FILENAME="mapl3_sample_dataset"
MAPL3_CMD=(
"miracl"
"flow"
"mapl3"
"--mwfc_raw_autoflor_tiff_folder" "mapl3_sample_dataset/Ex_647_Em_680_stitched"
"--mwfc_raw_signal_tiff_folder" "mapl3_sample_dataset/Ex_488_Em_525_stitched"
"--mwfc_results_folder" "mapl3/example_workflow"
"-mctn_ch" "signal"
"-mctn_vx" "1.8"
"-mctn_vz" "3"
"--mgp_brain_mask_erosion_flag" "True"
"--mps_dtype" "float32"
"--mrca_orient_code" "PLI"
"--mv_res_xy" "1.8"
"--mv_res_z" "3"
"--mv_downsample_yx_axis" "10"
"--mv_downsample_z_axis" "6"
"-mctn_d" "20"
"--mpp_intensity_threshold" "1"
"--mpp_tissue_percentage_threshold" "20"
"--mi_gpu_index" "all"
"--mi_save_prob_map" "True"
"--skip_conversion" "False"
"--skip_registration" "False"
"--skip_generate_patch" "False"
"--skip_preprocessing_parallel" "False"
"--skip_inference" "False"
"--skip_patch_stacking" "False"
"--skip_data_normalization" "False"
"--skip_skeletonization" "False"
"--skip_voxelized_skeletonization" "False"
"--skip_voxelized_normalization" "False"
"--skip_warped_voxelized_normalization" "False"
"--skip_warped_voxelized_skeletonization" "False"
"--skip_feat_extract_skeletonization" "False"
"--skip_feat_extract_normalization" "False"
"--skip_plot_warped_data" "False"
)

print_mapl3_cmd() {
    local cmd=("$@")

    printf "$ %s " "${cmd[0]} ${cmd[1]} ${cmd[2]}"
    echo " \\"

    for ((i=3; i<${#cmd[@]}; i+=2)); do
        printf "  %q %q" "${cmd[i]}" "${cmd[i+1]:-}"
        if (( i+2 < ${#cmd[@]} )); then
            echo " \\"
        else
            echo ""
        fi
    done
}

display_help() {
  cat <<EOF

-----------------------------------------------------------------

This script runs the complete MAPL3 workflow on a sample dataset.

The sample dataset will be downloaded automatically.

Things to note:

1) Please make sure that you are in the correct folder where you want to download the data 
   to and that the folder has the correct write permissions set for the container user.
2) Ideally this folder has been mounted into the Docker/Apptainer container from the host system
   to ensure that the data won't be deleted when the container is shut down.
3) You should at least have 1TB available for the dataset and the analysis results.
4) If the workflow fails for some reason or you decide to run it manually, run this
   script with the '-c' flag to print the full command that will be passed to MIRACL by 
   this script to stdout. You can then copy and use this command to run the worklfow on 
   the sample dataset manually.

-----------------------------------------------------------------

Usage: $0 [-h] [-c] [-k] [-p]

Options:
  -h    Display this help menu
  -c    Print the full MIRACL command for running the MAPL3 workflow on the sample dataset
  -k    Keep zip file instead of deleting it
  -p    Keep partial downloads instead of deleting them

-----------------------------------------------------------------

Run the script without any options to download the sample dataset and run the MAPL3 workflow.

-----------------------------------------------------------------

EOF
}

KEEP_ZIP=false
KEEP_PARTS=false

assemble_and_unzip() {
    local base_name="$1"
    local assembled_zip="${base_name}.zip"

    echo "Preparing dataset..."

    total_bytes=0
    for part in "${base_name}_part_"*; do
        total_bytes=$((total_bytes + $(stat -c%s "$part")))
    done

    echo "  Combining parts into ${assembled_zip}..."

    cat "${base_name}_part_"* | pv -s "$total_bytes" > "$assembled_zip"

    echo ""
    echo "  Parts combined successfully."

    if ! [[ "$KEEP_PARTS" == true ]]; then
        echo "  Removing temporary part files..."
        rm -f "${base_name}_part_"??
        echo "  Part files removed."
    else
        echo "  Keeping part files (-p flag set)."
    fi

    echo ""
    echo "Extracting ${assembled_zip}..."

    mkdir -p "$base_name"
    unzip -o "$assembled_zip" -d "$base_name"
    
    echo ""
    echo "  Extraction complete."

    if ! [[ "$KEEP_ZIP" == true ]]; then
        echo "  Removing combined zip file..."
        rm -f "$assembled_zip"
        echo "  Combined zip file deleted."
    else
        echo "  Keeping combined zip file (-k flag set)."
    fi

    echo ""
    echo "Dataset is ready."
}

download_file() {
  local base_url="$1"
  local base_name="$2"

  local parts=(aa ab ac ad ae af ag ah)
  local total=${#parts[@]}
  local part_idx=1

  echo ""
  echo "Downloading MAPl3 sample dataset..."
  echo "INFO: Depending on your internet connection, this could take a while (353GB)."
  echo "INFO: The dataset is split into ${total} parts and will be combined locally."
  echo ""

  for part in "${parts[@]}"; do
        local filename="${base_name}_part_${part}"
        local url="${base_url}/${filename}"

        echo "Downloading part ${part_idx}/${total} (${part})..."
        if wget -c -q --show-progress -O "$filename" "$url"; then
            echo "  Downloaded part ${part_idx}/${total}: ${filename}."
            ((++part_idx))
        else
            echo "  Failed to download part ${part_idx}: ${filename}."
            echo "  Do you have write permissions in the location?"
            return 1
        fi
        echo ""
    done

    echo "Dataset downloaded successfully."
    echo ""

    assemble_and_unzip "$base_name"
}

check_miracl_cmd() {
  # This essentially checks if the user is executing the script from within the container
  if ! command -v miracl >/dev/null 2>&1; then
      echo ""
      echo "-----------------------------------------------------------------"
      echo ""
      echo "ERROR: The 'miracl' command was not found."
      echo ""
      echo "-----------------------------------------------------------------"
      echo ""
      echo "Make sure you are running this script inside the Docker container that contains MIRACL."
      echo "This command will not work outside of the Docker container."
      echo ""
      echo "-----------------------------------------------------------------"
      echo ""
      return 1
  fi
}

run_mapl3_workflow() {
    # Make a copy of MAPL3_CMD
    # local cmd=("${MAPL3_CMD[@]}")
    local exec_cmd=(python /code/miracl/system/registry/run_mapl3_workflow.py "${MAPL3_CMD[@]:3}")

    echo ""
    echo "-----------------------------------------------------------------"
    echo ""
    echo "Running MAPL3 workflow on sample data using:"
    echo ""

    print_mapl3_cmd "${MAPL3_CMD[@]}"

    echo ""
    echo "Creating results folder..."
    mkdir -p mapl3/example_workflow

    # Run the command
    "${exec_cmd[@]}"
    local status=$?
    if [[ $status -ne 0 ]]; then
        echo "ERROR: MAPL3 workflow failed with exit code $status."
        return $status
    fi
}

print_command() {
  echo ""
  echo "-----------------------------------------------------------------"
  echo ""
  echo "This is the full command that is used by the script to run the MAPL3 workflow on the sample dataset:"
  echo ""
  echo "-----------------------------------------------------------------"
  echo ""
  print_mapl3_cmd "${MAPL3_CMD[@]}"
  echo ""
  echo "-----------------------------------------------------------------"
  echo ""
  echo "Copy the command and use it to run the workflow manually. Change the parameters as"
  echo "required and make sure that the path to the RAW input data is correct."
  echo ""
  echo "The sample data can be downloaded with the download_sample_data command."
  echo ""
  echo "-----------------------------------------------------------------"
  echo ""
}

parse_options() {
    while getopts ":hckp" opt; do
        case "$opt" in
            h) display_help; exit 0 ;;
            c) print_command; exit 0 ;;
            k) KEEP_ZIP=true ;;
            p) KEEP_PARTS=true ;;
            \?) echo "Unknown option: -$OPTARG. Use -h for an overview of all valid flag options." >&2; exit 1 ;;
        esac
    done

    shift $((OPTIND-1))
}

main() {
  check_miracl_cmd
  download_file "$MAPL3_SAMPLE_URL" "$MAPL3_DATASET_FILENAME"
  run_mapl3_workflow
}

parse_options "$@"
main
