general:
  model_name: 'unetr' # 'unetr' or 'unet'
  batch_size: 1
  crop_size: 96
  crop_number: 10
  checkpoint_period: 10
  max_epochs: 300
  validation_interval: 1
  early_stop_patience: 50
  model_trained_path: '/code/miracl/seg/models/unetr/best_metric_model.pth' # for unetr
  # model_trained_path: '/code/miracl/seg/models/unet/best_metric_model.pth' # for unet
  data_aug_prob: 0.7
  cache_rate_train: 0
  cache_rate_val: 0
unet:
  n_encoder_layers: 5
  channels_initial: 16
  num_res_unit: 2
  dropout: 0.2
unetr:
  feature_size: 16
  hidden_size: 768
  mlp_dim: 3072
  num_heads: 12
  dropout: 0.2
  res_block: True
loss:
  name: 'dicece' # 'dice' or 'dicece' or 'focaldice' or 'tversky'
optimizer:
  learning_rate: 0.0001
  weight_decay: 0.0
  
  

