from miracl.system.datamodels.datamodel_miracl_objs import (
    MiraclObj,
    ArgumentType,
    WidgetType,
)


class GeneratePatch:
    input = MiraclObj(
        id="8a82f37b-3d5a-45da-8ccb-d13728f13fb3",
        name="mgp_input",
        tags=["mapl3", "seg", "mapl3_flow"],
        cli_s_flag="i",
        cli_l_flag="input",
        flow={"mapl3": {"cli_s_flag": "mgp_i", "cli_l_flag": "mgp_input"}},
        cli_obj_type=ArgumentType.STRING,
        cli_help="input directory containing .tiff or .tif slices (default: None)",
        cli_required=True,
        gui_label=["Input folder"],
        gui_group={"mapl3": "main"},
        gui_order=[1],
        module="mapl3",
        module_group="seg",
        version_added="2.4.0",
        gui_widget_type=WidgetType.PATH_INPUT,
    )

    output = MiraclObj(
        id="beffa5d5-23c9-4152-8688-94724b6a829f",
        name="mgp_output",
        tags=["mapl3", "seg", "mapl3_flow"],
        cli_s_flag="o",
        cli_l_flag="output",
        flow={"mapl3": {"cli_s_flag": "mgp_o", "cli_l_flag": "mgp_output"}},
        cli_obj_type=ArgumentType.STRING,
        cli_help="path of output directory (default: None)",
        cli_required=True,
        gui_label=["Output folder"],
        gui_group={"mapl3": "main"},
        gui_order=[2],
        module="mapl3",
        module_group="seg",
        version_added="2.4.0",
        gui_widget_type=WidgetType.PATH_INPUT,
    )

    cpu_load = MiraclObj(
        id="98dcf83e-aa71-4da5-aae8-c102fd100bdd",
        name="mgp_cpu_load",
        tags=["mapl3", "seg", "mapl3_flow"],
        cli_s_flag="c",
        cli_l_flag="cpu_load",
        flow={"mapl3": {"cli_s_flag": "mgp_c", "cli_l_flag": "mgp_cpu_load"}},
        cli_obj_type=ArgumentType.FLOAT,
        cli_help="fraction of cpus to be used for parallelization. Value needs to be between 0-1 (default: %(default)s)",
        cli_required=False,
        obj_default=0.7,
        gui_label=["CPU load"],
        gui_group={"mapl3": "main"},
        gui_order=[3],
        module="mapl3",
        module_group="seg",
        version_added="2.4.0",
        gui_widget_type=WidgetType.DOUBLE_SPINBOX,
    )

    patch_size = MiraclObj(
        id="ebd46db3-d2f5-4c45-af3c-0e5c26a66520",
        name="mgp_patch_size",
        tags=["mapl3", "seg", "mapl3_flow"],
        cli_s_flag="p",
        cli_l_flag="patch_size",
        flow={"mapl3": {"cli_s_flag": "mgp_p", "cli_l_flag": "mgp_patch_size"}},
        cli_obj_type=ArgumentType.INTEGER,
        cli_help="the outputs will be patch size x patch size x patch size (default: %(default)s)",
        cli_required=False,
        obj_default=256,
        gui_label=["Path size"],
        gui_group={"mapl3": "main"},
        gui_order=[4],
        module="mapl3",
        module_group="seg",
        version_added="2.4.0",
        gui_widget_type=WidgetType.SPINBOX,
    )

    gamma = MiraclObj(
        id="a9fe8607-1a25-450e-8c71-401d4c12ff74",
        name="mgp_gamma",
        tags=["mapl3", "seg", "mapl3_flow"],
        cli_s_flag="g",
        cli_l_flag="gamma",
        flow={"mapl3": {"cli_s_flag": "mgp_g", "cli_l_flag": "mgp_gamma"}},
        cli_obj_type=ArgumentType.FLOAT,
        cli_help="gamma for gamma correction algorithm (default: %(default)s)",
        cli_required=False,
        obj_default=0.3,
        gui_label=["Gamma"],
        gui_group={"mapl3": "main"},
        gui_order=[5],
        module="mapl3",
        module_group="seg",
        version_added="2.4.0",
        gui_widget_type=WidgetType.DOUBLE_SPINBOX,
    )
