#!/usr/bin/env python

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miracl_conv_set_orient_qt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 660)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_gridLayout = QtWidgets.QGridLayout()
        self.image_gridLayout.setObjectName("image_gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.annotation_left_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.annotation_left_pushButton.setObjectName("annotation_left_pushButton")
        self.image_gridLayout.addWidget(self.annotation_left_pushButton, 1, 0, 1, 1)
        self.annotation_right_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.annotation_right_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.annotation_right_pushButton.setObjectName("annotation_right_pushButton")
        self.image_gridLayout.addWidget(self.annotation_right_pushButton, 1, 4, 1, 1)
        self.annotation_top_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.annotation_top_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.annotation_top_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.annotation_top_pushButton.setObjectName("annotation_top_pushButton")
        self.image_gridLayout.addWidget(self.annotation_top_pushButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.image_gridLayout)
        self.footer_gridLayout = QtWidgets.QGridLayout()
        self.footer_gridLayout.setObjectName("footer_gridLayout")
        self.image_number_label = QtWidgets.QLabel(self.centralwidget)
        self.image_number_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.image_number_label.setObjectName("image_number_label")
        self.footer_gridLayout.addWidget(self.image_number_label, 0, 3, 1, 1)
        self.next_image_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_image_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.next_image_pushButton.setObjectName("next_image_pushButton")
        self.footer_gridLayout.addWidget(self.next_image_pushButton, 0, 6, 1, 1)
        self.image_number_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.image_number_spinBox.setObjectName("image_number_spinBox")
        self.footer_gridLayout.addWidget(self.image_number_spinBox, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_gridLayout.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.prev_image_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.prev_image_pushButton.setObjectName("prev_image_pushButton")
        self.footer_gridLayout.addWidget(self.prev_image_pushButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.footer_gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 21))
        self.menubar.setObjectName("menubar")
        self.menuOrientation = QtWidgets.QMenu(self.menubar)
        self.menuOrientation.setObjectName("menuOrientation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOrientation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Input Tiff files"))
        self.annotation_left_pushButton.setText(_translate("MainWindow", "Annotation (Into Page)"))
        self.annotation_right_pushButton.setText(_translate("MainWindow", "Annotation"))
        self.annotation_top_pushButton.setText(_translate("MainWindow", "Annotation"))
        self.image_number_label.setText(_translate("MainWindow", "Image number"))
        self.next_image_pushButton.setText(_translate("MainWindow", "Next Image"))
        self.prev_image_pushButton.setText(_translate("MainWindow", "Prev Image"))
        self.menuOrientation.setTitle(_translate("MainWindow", "Orientation"))
