name: "CLARITY Conversion -> Registration workflow"
description: "Running TIFF to Nifti conversion and atlas registration on CLARITY method images"
version: "1.0"

vars:
  base_dir: "ref:conns.conv_reg_workflow_results_folder"
  tiff_folder: "ref:conns.conv_reg_workflow_raw_autoflor_tiff_folder"
  conv_nii: "pattern:{ref:vars.base_dir}/conv_final/{ref:conv.outnii}_{fn:dx_pad_zero('ref:conv.down')}x_down_{ref:conv.channame}_chan.nii.gz"

modules:
  CONV_REG_WORKFLOW_CONNECTORS@conns: {}
  CONV_TIFF_NII@conv: {}
  REG_CLAR_ALLEN@reg: {}

execution_order:
  - conns
  - conv
  - reg

data_flow:
  conns:
    output:
      tiff_folder: "ref:vars.tiff_folder"
      output_folder: "ref:vars.base_dir"

  conv: 
    input:
      tiff_folder: "ref:vars.tiff_folder"
      output_folder: "ref:vars.base_dir"
    output:
      conv_nii: "ref:vars.conv_nii"

  reg:
    input:
      nii_folder: "ref:vars.conv_nii"
      tiff_folder: "ref:vars.tiff_folder"
      output_path: "ref:vars.base_dir"
      chan_num: "ref:conv.channum"
      chan_prefix: "ref:conv.chanprefix"
