name: "MAPL3"
description: "Mapping Axonal Projections in Light-sheet Fluorescence Microscopy in 3D (MAPL3)"
version: "1.0"

vars:
  base_res_dir: "ref:conns.mapl3_workflow_results_folder"
  raw_autoflor_dir: "ref:conns.mapl3_workflow_raw_autoflor_tiff_folder"
  raw_signal_dir: "ref:conns.mapl3_workflow_raw_signal_tiff_folder"
  converted_nii: "pattern:{ref:vars.base_res_dir}/conv_final/{ref:conv.outnii}_{fn:dx_pad_zero('ref:conv.down')}x_down_{ref:conv.channame}_chan.nii.gz"
  brain_mask_folder: "pattern:{ref:vars.base_res_dir}/reg_final/annotation_hemi_{ref:reg.hemi}_{ref:reg.voxel_size}um_tiff_clar"
  clar_allen_reg_folder: "pattern:{ref:vars.base_res_dir}/clar_allen_reg"
  generated_patches: "pattern:{ref:vars.base_res_dir}/generated_patches"
  gen_patch_metadata_json: "pattern:{ref:vars.generated_patches}/metadata.json"
  preprocessed: "pattern:{ref:vars.base_res_dir}/preprocessing_parallel"
  inference_out_prob: "pattern:{ref:vars.base_res_dir}/inference/out_prob"
  normalized_data: "pattern:{ref:vars.base_res_dir}/normalized_raw_data"
  skeletonized_data: "pattern:{ref:vars.base_res_dir}/skeletonized"
  patch_stacking_metadata_file: "pattern:{ref:vars.generated_patches}/metadata.json"
  stacked_patches: "pattern:{ref:vars.base_res_dir}/stacked_patches"
  voxelized_normalization: "pattern:{ref:vars.base_res_dir}/voxelized_normalization"
  voxelized_skeletonization: "pattern:{ref:vars.base_res_dir}/voxelized_skeletonization"
  norm_ort2std_file: "pattern:{ref:vars.voxelized_normalization}/ort2std.txt"
  skel_ort2std_file: "pattern:{ref:vars.voxelized_skeletonization}/ort2std.txt"
  heatmaps_dir: "pattern:{ref:conns.mapl3_workflow_results_folder}/heatmaps"
  warped_results_dir: "pattern:{ref:conns.mapl3_workflow_results_folder}/warped_results"
  vox_res_skel_file: "pattern:{ref:vars.warped_results_dir}/voxelized_results_mapl3_skel_channel_allen_space.nii.gz"
  vox_res_norm_file: "pattern:{ref:vars.warped_results_dir}/voxelized_results_mapl3_norm_channel_allen_space.nii.gz"
  annotation_hemi_split_lbl_10um: "pattern:/code/atlases/ara/annotation/annotation_hemi_{ref:reg.hemi}_{ref:reg.voxel_size}um.nii.gz"

modules:
  MAPL3_WORKFLOW_CONNECTORS@conns: {}
  CONV_TIFF_NII@conv: {}
  REG_CLAR_ALLEN@reg: {}
  MAPL3_GENERATE_PATCH@gen_patch: {}
  MAPL3_PREPROCESSING_PARALLEL@preproc_para: {}
  MAPL3_INFERENCE@inference: {}
  MAPL3_PATCH_STACKING@patch_stacking: {}
  MAPL3_RAW_DATA_NORMALIZATION@normalization: {}
  MAPL3_SKELETONIZATION@skeletonization: {}
  MAPL3_VOXELIZATION@norm_vox: {}
  MAPL3_VOXELIZATION@norm_skel: {}
  MAPL3_WARP_CLAR_ALLEN@warp_vox:
    hooks:
      pre_run:
        - "fn:create_ort2std_file('ref:vars.raw_signal_dir', 'ref:reg.orient_code', 'ref:vars.voxelized_normalization', True)"
      post_run:
        - "fn:move_warping_reg_final_contents('pattern:{ref:vars.base_res_dir}/warped_results', True)"
  MAPL3_WARP_CLAR_ALLEN@warp_skel:
    hooks:
      pre_run:
        - "fn:create_ort2std_file('ref:vars.raw_signal_dir', 'ref:reg.orient_code', 'ref:vars.voxelized_skeletonization', True)"
      post_run:
        - "fn:move_warping_reg_final_contents('pattern:{ref:vars.base_res_dir}/warped_results', True)"
  MAPL3_PLOT_WARPED_DATA@plot_warped_skel:
    hooks:
      pre_run:
        - "fn:ensure_folder_exists('ref:vars.heatmaps_dir', False)"
  MAPL3_PLOT_WARPED_DATA@plot_warped_norm: {}
  MAPL3_FEAT_EXTRACT@feat_extract_skel: {}
  MAPL3_FEAT_EXTRACT@feat_extract_norm: {}

execution_order:
  - conns
  - conv
  - reg
  - gen_patch
  - preproc_para
  - inference
  - patch_stacking
  - normalization
  - skeletonization
  - norm_vox
  - norm_skel
  - warp_vox
  - warp_skel
  - plot_warped_skel
  - plot_warped_norm
  - feat_extract_skel
  - feat_extract_norm

data_flow:
  conns:
    output:
      base_res_dir:    "ref:vars.base_res_dir"
      raw_autoflor_dir: "ref:vars.raw_autoflor_dir"
      raw_signal_dir:  "ref:vars.raw_signal_dir"
  conv:
    input:
      tiff_folder:   "ref:vars.raw_autoflor_dir"
      output_folder: "ref:vars.base_res_dir"
    output:
      converted_nii: "ref:vars.converted_nii"
  reg:
    input:
      nii_folder:  "ref:vars.converted_nii"
      tiff_folder: "ref:vars.raw_autoflor_dir"
      output_path: "ref:vars.base_res_dir"
      chan_num:    "ref:conv.channum"
      chan_prefix: "ref:conv.chanprefix"
    output:
      brain_mask_folder:    "ref:vars.brain_mask_folder"
      clar_allen_reg_folder: "ref:vars.clar_allen_reg_folder"
  gen_patch:
    input:
      input:      "ref:vars.raw_signal_dir"
      brain_mask: "ref:vars.brain_mask_folder"
      out_dir:    "ref:vars.base_res_dir"
    output:
      generated_patches: "ref:vars.generated_patches"
      gen_patch_metadata_json: "ref:vars.gen_patch_metadata_json"
  preproc_para:
    input:
      input:   "ref:vars.generated_patches"
      out_dir: "ref:vars.base_res_dir"
      metadata_file: "ref:vars.gen_patch_metadata_json"
    output:
      preprocessed: "ref:vars.preprocessed"
  inference:
    input:
      config:     "literal:/code/miracl/seg/mapl3/config_finetune.yml"
      input_dir:  "ref:vars.preprocessed"
      model_path: "literal:/code/miracl/seg/mapl3/models/best_metric_model.pth"
      out_dir:    "ref:vars.base_res_dir"
    output:
      inference_out_prob: "ref:vars.inference_out_prob"
  patch_stacking:
    input:
      input_dir:     "ref:vars.inference_out_prob"
      out_dir:       "ref:vars.base_res_dir"
      tiff_folder:   "ref:vars.raw_signal_dir"
      metadata_file: "ref:vars.patch_stacking_metadata_file"
    output:
      stacked_patches: "ref:vars.stacked_patches"
  normalization:
    input:
      input_dir:   "ref:vars.stacked_patches"
      tiff_folder: "ref:vars.raw_signal_dir"
      out_dir:     "ref:vars.base_res_dir"
      brain_mask:  "ref:vars.brain_mask_folder"
    output:
      normalized_data: "ref:vars.normalized_data"
  skeletonization:
    input:
      input_dir:   "ref:vars.stacked_patches"
      brain_mask:  "ref:vars.brain_mask_folder"
      out_dir:     "ref:vars.base_res_dir"
      tiff_folder: "ref:vars.raw_signal_dir"
    output:
      skeletonized_data: "ref:vars.skeletonized_data"
  norm_vox:
    input:
      input_dir: "ref:vars.normalized_data"
      out_dir:   "ref:vars.voxelized_normalization"
    output:
      voxelized_normalization: "ref:vars.voxelized_normalization"
  norm_skel:
    input:
      input_dir: "ref:vars.skeletonized_data"
      out_dir:   "ref:vars.voxelized_skeletonization"
    output:
      voxelized_skeletonization: "ref:vars.voxelized_skeletonization"
  warp_vox:
    input:
      reg_dir:      "ref:vars.clar_allen_reg_folder"
      nii_folder:   "pattern:{ref:vars.voxelized_normalization}/{ref:norm_vox.out_name}.nii.gz"
      ort2std_file: "ref:vars.norm_ort2std_file"
      seg_channel:  "literal:mapl3_norm"
    output:
      vox_res_norm_file: "ref:vars.vox_res_norm_file"
  warp_skel:
    input:
      reg_dir:      "ref:vars.clar_allen_reg_folder"
      nii_folder:   "pattern:{ref:vars.voxelized_skeletonization}/{ref:norm_skel.out_name}.nii.gz"
      ort2std_file: "ref:vars.skel_ort2std_file"
      seg_channel:  "literal:mapl3_skel"
    output:
      vox_res_skel_file: "ref:vars.vox_res_skel_file"
  plot_warped_skel:
    input:
      pvalue:      "ref:vars.vox_res_skel_file"
      vox:         "literal:25"
      sigma:       "literal:2"
      dir_outfile: "ref:vars.heatmaps_dir"
      outfile:     "literal:heatmap_mapl3_skel"
  plot_warped_norm:
    input:
      pvalue:      "ref:vars.vox_res_norm_file"
      vox:         "literal:25"
      sigma:       "literal:2"
      dir_outfile: "ref:vars.heatmaps_dir"
      outfile:     "literal:heatmap_mapl3_norm"
  feat_extract_skel:
    input:
      seg: "ref:vars.vox_res_skel_file"
      lbl: "ref:vars.annotation_hemi_split_lbl_10um"
  feat_extract_norm:
    input:
      seg: "ref:vars.vox_res_norm_file"
      lbl: "ref:vars.annotation_hemi_split_lbl_10um"
