mapl3_inference:
  script: "python /code/miracl/seg/mapl3/mapl3_inference.py"
  obj_class: "miracl.system.objs.objs_seg.objs_mapl3.objs_mapl3_inference.Inference"
  module_type: "MODULE"
  runner: "miracl.system.workflow.runners.generic_runner.generic_runner"
  flag_map: {}
  execute: true
