CONV_TIFF_NII:
  script: "python /code/miracl/conv/miracl_conv_convertTIFFtoNII.py"
  obj_class: "miracl.system.objs.objs_conv.objs_tiff_to_nii.objs_tiff_to_nii.ConvTiffNiiObjs"
  module_type: "MODULE"
  runner: "miracl.system.workflow.runners.generic_runner.generic_runner"
  flag_map: {}
  execute: true
